//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmlerKatmanli.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmlerDBEntities : DbContext
    {
        public FilmlerDBEntities()
            : base("name=FilmlerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Filmler> Filmler { get; set; }
        public DbSet<FilmOyuncular> FilmOyuncular { get; set; }
        public DbSet<Oyuncular> Oyuncular { get; set; }
        public DbSet<Yonetmenler> Yonetmenler { get; set; }
    }
}
