//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmlerKatmanli.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oyuncular
    {
        public Oyuncular()
        {
            this.FilmOyuncular = new HashSet<FilmOyuncular>();
        }
    
        public int OyuncuId { get; set; }
        public string OyuncuAdi { get; set; }
        public string OyuncuSoyadi { get; set; }
    
        public virtual ICollection<FilmOyuncular> FilmOyuncular { get; set; }
    }
}
