//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmlerKatmanli.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class Yonetmenler
    {
        public Yonetmenler()
        {
            this.Filmler = new HashSet<Filmler>();
        }

        public int YonetmenId { get; set; }
        public string YonetmenAdi { get; set; }
        public string YonetmenSoyadi { get; set; }
        public string AdSoyad
        {
            get
            {
                return YonetmenAdi + " " + YonetmenSoyadi;
            }
        }

        public virtual ICollection<Filmler> Filmler { get; set; }
    }
}
